language: node_js
node_js:
  - "11"

env:
  - DIR=.
  - DIR=example/hello-world

install:
  - (cd $DIR; npm install)

script:
  - (cd $APP; yarn run lint)
  - (cd $APP; yarn test)
  - (cd $APP; yarn run build)
